name: pyphoon
adopt-info: pyphoon
summary: ASCII Art Phase of the Moon!
description: |  
  ASCII Art Phase of the Moon (Python version)

license: MIT

base: core18
grade: stable 
confinement: strict

apps:
  pyphoon:
    command: pyphoon
    plugs:
      - network
     
parts: 
  pyphoon:
    source: https://github.com/chubin/pyphoon
    source-type: git
    plugin: python
    python-version: python2
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
    
    build-packages:
      - python
      - python-dateutil
      
    stage-packages:
      - python
      - python-dateutil
